# Generated by Django 6.0.3 on 2026-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.ImageField(null=True, upload_to='note_photos/'),
        ),
    ]
