# Generated by Django 6.0.3 on 2026-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_alter_note_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='word_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
